# This code includes commands to generate figures of freshwater residence 
# presented in the manuscript.

# Initial setup ----
library(tidyverse)
library(lubridate)
library(HDInterval)
library(ggdist)

# Some of the data generated by the data processing file are needed
source("codes/R/02-process_fish_data.R")

out <- readRDS(paste("outputs/out_fit_dat.rds", sep = ""))
fit <- out$fit
jdat <- out$jdat
mcmc <- fit$samples
ns <- fit$mcmc.info$n.samples

# Make predictions of freshwater residence ----

len_rgn <- select(res_dat, rel_dt, length) |>
  mutate(rel_dt = case_when(as_date(rel_dt) ==  ymd("2021-05-23") ~ "m23",
                            as_date(rel_dt) ==  ymd("2021-06-09") ~ "j09",
                            as_date(rel_dt) ==  ymd("2021-06-19") ~ "j19"),
         z_length = (length - mean(length)) / sd(length)) |>
  group_by(rel_dt) |>
  summarize(min = min(z_length),
            max = max(z_length))

nd_m23 <- expand.grid(rel_ste = c("lwr", "lke", "upr"),
                      rel_dt = "m23",
                      # Add zero to sequence to ensure we have predictions at 
                      # the mean
                      z_length = c(0, seq(filter(len_rgn, rel_dt == "m23")$min,
                                     filter(len_rgn, rel_dt == "m23")$max,
                                     0.1)))

nd_j09 <- expand.grid(rel_ste = c("lwr", "lke", "upr"),
                      rel_dt = "j09",
                      # Add zero to sequence to ensure we have predictions at 
                      # the mean
                      z_length = c(0, seq(filter(len_rgn, rel_dt == "j09")$min,
                                     filter(len_rgn, rel_dt == "j09")$max,
                                     0.1)))

nd_j19 <- expand.grid(rel_ste = c("lwr", "lke", "upr"),
                      rel_dt = "j19",
                      # Add zero to sequence to ensure we have predictions at 
                      # the mean
                      z_length = c(0, seq(filter(len_rgn, rel_dt == "j19")$min,
                                     filter(len_rgn, rel_dt == "j19")$max,
                                     0.1)))

nd <- rbind(nd_m23, nd_j09, nd_j19)

nd <- as.data.frame(model.matrix(~ z_length + rel_ste * rel_dt, nd)) %>%
  select(z_length:rel_dtj19) %>%
  rename(len = z_length, lke = rel_stelke, upr = rel_steupr,
         j09 = rel_dtj09, j19 = rel_dtj19) 

pred <-  tibble(a_r = fit$sims.list$alpha.r,
                b_len = fit$sims.list$beta.r[, 1],
                b_upr = fit$sims.list$beta.r[, 2],
                b_lke = fit$sims.list$beta.r[, 3],
                b_j09 = fit$sims.list$beta.r[, 4],
                b_j19 = fit$sims.list$beta.r[, 5],
                b_lke_j09 = fit$sims.list$beta.r[, 6],
                b_lke_j19 = fit$sims.list$beta.r[, 7],
                b_upr_j09 = fit$sims.list$beta.r[, 8],
                b_upr_j19 = fit$sims.list$beta.r[, 9],
                v_brg_m23 = fit$sims.list$nu.r[, 1],
                v_lke_m23 = fit$sims.list$nu.r[, 2],
                v_upr_m23 = fit$sims.list$nu.r[, 3],
                v_brg_j09 = fit$sims.list$nu.r[, 4],
                v_lke_j09 = fit$sims.list$nu.r[, 5],
                v_upr_j09 = fit$sims.list$nu.r[, 6],
                v_brg_j19 = fit$sims.list$nu.r[, 7],
                v_lke_j19 = fit$sims.list$nu.r[, 8],
                v_upr_j19 = fit$sims.list$nu.r[, 9]) %>%
  expand(nesting(a_r, b_len, b_upr, b_lke, b_j09, b_j19, b_lke_j09,
                 b_lke_j19, b_upr_j09, b_upr_j19, v_brg_m23, v_lke_m23,
                 v_upr_m23, v_brg_j09, v_lke_j09, v_upr_j09, v_brg_j19,
                 v_lke_j19, v_upr_j19), 
         nesting(nd)) %>% 
  mutate(lam = exp(a_r + b_len * len + 
                     b_lke * lke + b_upr * upr +
                     b_j09 * j09 + b_j19 * j19 + 
                     b_lke_j09 * lke * j09 + b_lke_j19 * lke * j19 +
                     b_upr_j09 * upr * j09 + b_upr_j19 * upr * j19),
         v = (1 - lke) * (1 - upr) * (1 - j09) * (1 - j19) * v_brg_m23 + 
             (1 - lke) * (1 - upr) * j09 * v_brg_j09 + 
             (1 - lke) * (1 - upr) * j19 * v_brg_j19 +
             lke * (1 - j09) * (1 - j19) * v_lke_m23 + 
             lke * j09 * v_lke_j09 + 
             lke * j19 * v_lke_j19 +
             upr * (1 - j09) * (1 - j19) * v_upr_m23 + 
             upr * j09 * v_upr_j09 + 
             upr * j19 * v_upr_j19,
         r = (1 / lam) * gamma((v + 1) / v) / gamma(1), 
         rel_ste = case_when(lke == 0 & upr == 0 ~ "Lower River",
                             lke == 1 ~ "Lake",
                             upr == 1 ~ "Upper River"),
         rel_ste = factor(rel_ste, levels = c("Lower River", "Lake", "Upper River")),
         rel_dt = case_when(j09 == 0 & j19 == 0 ~ "May 23",
                            j09 == 1 ~ "June 09",
                            j19 == 1 ~ "June 19"),
         rel_dt = factor(rel_dt, levels = c("May 23", "June 09", "June 19")))

pred_summ <- filter(pred, len == 0) %>% 
  group_by(rel_ste, rel_dt) %>%
  summarize(mdn = median(r),
            lwr = hdi(r, credMass = 0.95)[1],
            upr = hdi(r, credMass = 0.95)[2])

pred_summ_len <- pred %>% 
  group_by(rel_ste, rel_dt, len) %>%
  summarize(mdn = median(r),
            lwr = hdi(r, credMass = 0.95)[1],
            upr = hdi(r, credMass = 0.95)[2]) %>%
  # You may need to run code in 02-fit_model.R to create exit_data object. The
  # command below will convert standardized (SD) length values to the original 
  # measurements in mm.
  mutate(len_mm = len * sd(res_dat$length) + mean(res_dat$length))


# Figure 2 - Plot of predictions of freshwater residence by length ----

jpeg("plots/Figure_2.jpg", res = 300, unit = "cm", height = 20, width = 30)

lbl <- data.frame(rel_dt = factor(c("May 23", "June 09", "June 19"),
                                      levels = c("May 23", "June 09", "June 19")),
                  label = c("(a)", "(b)", "(c)"))

ggplot(pred_summ_len, aes(x = len_mm, y = mdn, colour = rel_ste,
                          fill = rel_ste)) +
         geom_ribbon(aes(ymin = lwr, ymax = upr), alpha = 0.2, col = "white") +
         geom_line() +
         xlab("Fork length (mm)") +
         ylab("Freshwater residence (days)") + 
         labs(color = "Release Site", fill = "Release Site") +
         geom_text(data = lbl, inherit.aes = FALSE, aes(x = 100, y = 60, label = label),
                   size = 5) +
         scale_y_continuous(breaks = seq(0, 60, 5),limits = c(0, 60)) +
         scale_colour_manual(values = c("#DBA037", "#3A7BB3", "#CE7A3A")) +
         scale_fill_manual(values = c("#DBA037", "#3A7BB3", "#CE7A3A")) +
         facet_wrap(~ rel_dt) +
         theme_bw() +
         theme(legend.position = "top",
               legend.title = element_blank(),
               panel.grid = element_blank(),
               axis.title.y = element_text(size = 16, margin = unit(c(0, 5, 0, 0), "mm")),
               axis.title.x = element_text(size = 16, margin = unit(c(5, 0, 0, 0), "mm")),
               axis.text = element_text(size = 14),
               strip.text = element_text(size = 14),
               legend.text = element_text(size = 14))

dev.off()

# Figure 3 - Plot predictions of freshwater residence by release site and date ----

jpeg("plots/Figure_3.jpg", res = 300, unit = "cm", height = 20, width = 30)

ggplot(filter(pred, len == 0), aes(x = rel_ste, y = r)) + 
  stat_gradientinterval(fill_type = "gradient", point_interval = "median_hdi",
                        fill = "gray40", .width = c(0.95), fatten_point = 2.5,
                        linewidth = 1.5) +
  geom_text(data = lbl, inherit.aes = FALSE, aes(x = 0.75, y = 35, label = label),
            size = 5) +
  scale_y_continuous(breaks = seq(0, 40, 5)) +
  ylab("Freshwater residence (days)") +
  xlab("Release site") +
  facet_wrap(~ rel_dt) +
  theme_bw() +
  theme(legend.position = "none",
        legend.text = element_text(size = 12),
        panel.grid = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 16, margin = margin(t = 12)),
        axis.title.y = element_text(size = 16, margin = margin(r = 12)),
        strip.text = element_text(size = 14))

dev.off()
